{ config, lib, ... }:
let
  colors = config.lib.stylix.colors.withHashtag;

  # One tint, meaning "this window is remote" -- never which machine. It has
  # to read through the terminal's 0.8 opacity over base00 (near-black), so
  # it is dark but saturated. Warm, to match the amber ssh prompt.
  remoteTint = "#2a1a08";
  localTint = colors.base00;
in
{
  # One source of truth, sourced both by the zsh wrapper below and by the
  # ssh-desktop / ssh-laptop scripts, which are separate binaries and so
  # never see the shell function.
  xdg.configFile."ssh-tint.sh".text = ''
    # Generated by modules/home/zsh/ssh_tint.nix -- do not edit.
    # Ghostty implements OSC 11 (set background) but not OSC 111 (reset), so
    # clearing has to name the colour. Taking it from Stylix keeps it correct
    # if the theme changes.
    ssh_tint_set() {
      printf '\033]11;${remoteTint}\007'
    }

    ssh_tint_clear() {
      # Still inside an outer ssh session? Then the window is still remote.
      if [ -n "$SSH_CONNECTION" ]; then
        printf '\033]11;${remoteTint}\007'
      else
        printf '\033]11;${localTint}\007'
      fi
    }
  '';

  programs.zsh.initContent = lib.mkAfter ''
    # Tint the terminal background while an ssh session is open, so a remote
    # window is obvious before you even read the prompt. This wraps ssh
    # *locally* on purpose: the tint is always restored when ssh returns.
    # Setting it from the remote's zshrc instead would leave the window
    # tinted for good whenever the link dropped before the shell could clean
    # up. Wrapping locally also means it works for hosts we do not control.
    source ${config.xdg.configHome}/ssh-tint.sh

    ssh() {
      # Leave non-terminal stdout alone: scripts, pipes, git-over-ssh.
      if [[ ! -t 1 || -z $TERM || $TERM == dumb ]]; then
        command ssh "$@"
        return
      fi

      # A function-scoped EXIT trap fires on normal return *and* when SIGINT
      # unwinds the function; an `always` block only covers the former.
      trap 'ssh_tint_clear' EXIT INT
      ssh_tint_set
      command ssh "$@"
    }
  '';
}
